dist: bionic # required for Python >= 3.7
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3
install:
  - pip install flake8
  - pip install coverage
  - pip install coveralls
  - pip install mock
  - pip install nose
script:
  - make tests-coverage
  - make lint
after_success:
  - coveralls
